services:
  backend:
    build:
      context: .
      dockerfile: dockerfile.backend
    ports:
      - "8443:8443"
    volumes:
      - .:/app
      - ./certs:/app/certs:ro
      - ./secrets:/app/secrets:ro
    env_file:
      - .env
    command: >
      uvicorn api_server.main:app
      --host 0.0.0.0
      --port 8443
      --reload
      --ssl-keyfile=/app/certs/key.pem
      --ssl-certfile=/app/certs/cert.pem

  frontend:
    build:
      context: ./frontend
      dockerfile: dockerfile.frontend
    ports:
      - "3000:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend