services:
  backend:
    build:
      context: ./App
      dockerfile: ../dockerfile.backend
    ports:
      - "8443:8443"
    volumes:
      - .:/app
      - ./certs:/app/certs:ro
      - ./secrets:/app/secrets:ro
    env_file:
      - .env
    command: >
      uvicorn api_server.main:app
      --host 0.0.0.0
      --port 8443
      --reload
      --ssl-keyfile=${SSL_KEY_FILE}
      --ssl-certfile=${SSL_CERT_FILE}

  frontend:
    build:
      context: ./frontend
      dockerfile: dockerfile.frontend
    ports:
      - "3000:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend
    environment:
      - VITE_API_BASE_URL=https://localhost:8443
