services:
  backend:
    build:
      # CRITICAL FIX: Context is now the project root to include the 'App' directory.
      context: .
      # CRITICAL FIX: Dockerfile path is now relative to the new context.
      dockerfile: ./backend/dockerfile.backend
    ports:
      - "8443:8443"
    volumes:
      # This mounts the entire project for live-reloading of all code.
      - .:/app
    # CRITICAL FIX: The command now points to the module using its full path from the project root.
    command: uvicorn App.api_server.app:app --host 0.0.0.0 --port 8443 --ssl-keyfile ./certs/key.pem --ssl-certfile ./certs/cert.pem --reload

  frontend:
    build:
      context: ./frontend
      dockerfile: dockerfile.frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    command: ["npm", "run", "dev"]